# -*- coding: utf-8 -*-
"""UI 文案补充词典(第二层)。

`i18n.py` 的 Z 表是主词典;这里收**后续迭代中零散补进界面的文案**(原先直接写成中文字面量,
切语言时不会跟着变)。`i18n.tr()` 会先查主词典、再查本表,都没命中才回退到 key。

15 种语言全覆盖;新增条目时按 langs 顺序给出 15 个值,顺序不可错:
    zh en ja ko ar hi id th tr vi fr de es pt it
"""
from __future__ import annotations

LANGS = ["zh", "en", "ja", "ko", "ar", "hi", "id", "th", "tr", "vi", "fr", "de", "es", "pt", "it"]

# key: [zh, en, ja, ko, ar, hi, id, th, tr, vi, fr, de, es, pt, it]
S: dict[str, list[str]] = {
    # ── 通用动作 / 状态 ──
    "u_name": ["名称", "Name", "名前", "이름", "الاسم", "नाम", "Nama", "ชื่อ", "Ad", "Tên",
               "Nom", "Name", "Nombre", "Nome", "Nome"],
    "u_save": ["保存", "Save", "保存", "저장", "حفظ", "सहेजें", "Simpan", "บันทึก", "Kaydet",
               "Lưu", "Enregistrer", "Speichern", "Guardar", "Salvar", "Salva"],
    "u_cancel": ["取消", "Cancel", "キャンセル", "취소", "إلغاء", "रद्द", "Batal", "ยกเลิก",
                 "İptal", "Hủy", "Annuler", "Abbrechen", "Cancelar", "Cancelar", "Annulla"],
    "u_apply": ["应用", "Apply", "適用", "적용", "تطبيق", "लागू", "Terapkan", "ใช้", "Uygula",
                "Áp dụng", "Appliquer", "Anwenden", "Aplicar", "Aplicar", "Applica"],
    "u_delete": ["删除", "Delete", "削除", "삭제", "حذف", "हटाएँ", "Hapus", "ลบ", "Sil",
                 "Xóa", "Supprimer", "Löschen", "Eliminar", "Excluir", "Elimina"],
    "u_processing": ["处理中…", "Processing…", "処理中…", "처리 중…", "جارٍ المعالجة…", "प्रसंस्करण…",
                     "Memproses…", "กำลังประมวลผล…", "İşleniyor…", "Đang xử lý…", "Traitement…",
                     "Verarbeitung…", "Procesando…", "Processando…", "Elaborazione…"],
    "u_loading": ["加载中…", "Loading…", "読み込み中…", "불러오는 중…", "جارٍ التحميل…", "लोड हो रहा है…",
                  "Memuat…", "กำลังโหลด…", "Yükleniyor…", "Đang tải…", "Chargement…", "Wird geladen…",
                  "Cargando…", "Carregando…", "Caricamento…"],
    "u_close": ["关闭", "Close", "閉じる", "닫기", "إغلاق", "बंद", "Tutup", "ปิด", "Kapat", "Đóng",
                "Fermer", "Schließen", "Cerrar", "Fechar", "Chiudi"],
    "u_add": ["新增", "Add", "追加", "추가", "إضافة", "जोड़ें", "Tambah", "เพิ่ม", "Ekle", "Thêm",
              "Ajouter", "Hinzufügen", "Añadir", "Adicionar", "Aggiungi"],
    "u_edit": ["编辑", "Edit", "編集", "편집", "تحرير", "संपादित", "Edit", "แก้ไข", "Düzenle", "Sửa",
               "Modifier", "Bearbeiten", "Editar", "Editar", "Modifica"],
    "u_refresh": ["刷新", "Refresh", "更新", "새로고침", "تحديث", "ताज़ा", "Segarkan", "รีเฟรช",
                  "Yenile", "Làm mới", "Actualiser", "Aktualisieren", "Actualizar", "Atualizar",
                  "Aggiorna"],
    "u_download": ["下载", "Download", "ダウンロード", "다운로드", "تنزيل", "डाउनलोड", "Unduh",
                   "ดาวน์โหลด", "İndir", "Tải xuống", "Télécharger", "Herunterladen", "Descargar",
                   "Baixar", "Scarica"],
    "u_apply_all": ["全部应用", "Apply all", "すべて適用", "전체 적용", "تطبيق الكل", "सभी लागू करें",
                    "Terapkan semua", "ใช้ทั้งหมด", "Tümünü uygula", "Áp dụng tất cả",
                    "Tout appliquer", "Alle anwenden", "Aplicar todo", "Aplicar tudo", "Applica tutto"],
    "u_view_large": ["点击查看大图", "Click to view large", "クリックで拡大", "클릭하여 크게 보기",
                     "انقر لعرض أكبر", "बड़ा देखने के लिए क्लिक करें", "Klik untuk memperbesar",
                     "คลิกเพื่อดูขนาดใหญ่", "Büyük görüntülemek için tıkla", "Bấm để xem lớn",
                     "Cliquez pour agrandir", "Klicken für große Ansicht", "Clic para ver grande",
                     "Clique para ver grande", "Clic per vedere grande"],
    "u_drafting": ["起草中", "Drafting…", "下書き中…", "초안 작성 중…", "جارٍ الصياغة…", "प्रारूप बना रहे हैं…",
                   "Menyusun…", "กำลังร่าง…", "Taslaklanıyor…", "Đang soạn…", "Rédaction…",
                   "Entwurf wird erstellt…", "Redactando…", "Redigindo…", "Bozza in corso…"],
    # ── 项目设置 ──
    "u_genre": ["题材", "Genre", "ジャンル", "장르", "النوع", "शैली", "Genre", "ประเภท", "Tür",
                "Thể loại", "Genre", "Genre", "Género", "Gênero", "Genere"],
    "u_intro": ["简介", "Synopsis", "あらすじ", "소개", "ملخص", "सारांश", "Ringkasan", "เรื่องย่อ",
                "Özet", "Tóm tắt", "Résumé", "Kurzfassung", "Sinopsis", "Sinopse", "Sintesi"],
    "u_appearance": ["外貌", "Appearance", "外見", "외모", "المظهر", "रूप", "Penampilan", "รูปลักษณ์",
                     "Dış görünüş", "Ngoại hình", "Apparence", "Aussehen", "Apariencia", "Aparência",
                     "Aspetto"],
    "u_world": ["世界观", "Worldbuilding", "世界観", "세계관", "العالم", "दुनिया", "Dunia",
                "โลกทัศน์", "Dünya", "Thế giới", "Univers", "Welt", "Universo", "Universo",
                "Mondi"],
    "u_outline": ["总纲", "Outline", "大綱", "개요", "المخطط العام", "रूपरेखा", "Garis besar",
                  "โครงเรื่อง", "Ana hat", "Dàn ý", "Plan général", "Gliederung", "Esquema",
                  "Esboço", "Struttura"],
    "u_contract": ["故事合约", "Story contract", "物語契約", "이야기 계약", "عقد القصة", "कहानी का संक",
                   "Kontrak cerita", "สัญญาเรื่อง", "Hikâye sözleşmesi", "Hợp đồng truyện",
                   "Contrat narratif", "Storyvertrag", "Contrato de historia", "Contrato de história",
                   "Contratto narrativo"],
    "u_chapter_plan": ["章节计划", "Chapter plan", "章立て", "장차트 계획", "خطة الفصول", "अध्याय योजना",
                       "Rencana bab", "แผนบท", "Bölüm planı", "Kế hoạch chương", "Plan des chapitres",
                       "Kapitelplan", "Plan de capítulos", "Plano de capítulos", "Piano dei capitoli"],
    "u_main_characters": ["主要角色", "Main characters", "主要登場人物", "주요 인물", "الشخصيات الرئيسية",
                          "मुख्य पात्र", "Tokoh utama", "ตัวละครหลัก", "Ana kişiler", "Nhân vật chính",
                          "Personnages principaux", "Hauptfiguren", "Personajes principales",
                          "Personagens principais", "Personaggi principali"],
    "u_role": ["角色定位", "Role", "役割", "역할", "الدور", "भूमिका", "Peran", "บทบาท", "Rol", "Vai trò",
               "Rôle", "Rolle", "Papel", "Papel", "Ruolo"],
    "u_location": ["地点", "Location", "場所", "장소", "المكان", "स्थान", "Lokasi", "สถานที่",
                   "Konum", "Địa điểm", "Lieu", "Ort", "Ubicación", "Local", "Luogo"],
    "u_time": ["时间", "Time", "時間", "시간", "الوقت", "समय", "Waktu", "เวลา", "Zaman", "Thời gian",
               "Heure", "Zeit", "Hora", "Hora", "Tempo"],
    "u_description": ["描述", "Description", "説明", "설명", "الوصف", "विवरण", "Deskripsi",
                      "คำอธิบาย", "Açıklama", "Mô tả", "Description", "Beschreibung", "Descripción",
                      "Descrição", "Descrizione"],
    "u_service": ["服务", "Service", "サービス", "서비스", "الخدمة", "सेवा", "Layanan", "บริการ",
                  "Hizmet", "Dịch vụ", "Service", "Dienst", "Servicio", "Serviço", "Servizio"],
    "u_style": ["风格", "Style", "スタイル", "스타일", "النمط", "शैली", "Gaya", "สไตล์", "Stil",
                "Phong cách", "Style", "Stil", "Estilo", "Estilo", "Stile"],
    "u_creative_desc": ["创意描述", "Creative brief", "企画の意図", "창작 아이디어", "وصف الفكرة",
                        "रचनात्मक विवरण", "Butiran kreatif", "แนวคิดสร้างสรรค์",
                        "Yaratıcı açıklama", "Mô tả ý tưởng", "Description créative",
                        "Kreativbeschreibung", "Descripción creativa", "Descrição criativa",
                        "Descrizione creativa"],
    "u_whole_placeholder": ["一句话简介(可选)", "One-line synopsis (optional)",
                            "一言紹介文(任意)", "한 줄 소개(선택)",
                            "نبذة من سطر واحد(اختياري)", "एक पंक्ति सारांश(वैकल्पिक)",
                            "Ringkasan satu baris(opsional)", "สรุปบรรทัดเดียว(ไม่บังคับ)",
                            "Tek satır özet(isteğe bağlı)", "Tóm tắt một dòng(tùy chọn)",
                            "Synopsis en une ligne(facultatif)", "Einzeiler(optional)",
                            "Synopsis de una línea(opcional)", "Synopsis de uma linha(opcional)",
                            "Sintesi in una riga(opzionale)"],
    "status_marked": ["已标记为", "Marked as", "マークしました", "로 표시됨", "تم التعليم كـ",
                      "के रूप में चिह्नित", "Ditandai sebagai", "ทำเครื่องหมายว่า",
                      "Olarak işaretlendi", "Đã đánh dấu", "Marqué comme", "Markiert als",
                      "Marcado como", "Marcado como", "Contrassegnato come"],
    "no_snapshot_to_restore": ["没有可恢复的原始形象快照", "No original snapshot to restore",
        "Aucun instantané d'origine à restaurer", "復元すべき元のイメージがありません",
        "لا توجد لقطة أصلية للاستعادة", "को पुनर्स्थापित करने के लिए मूल स्नैपशॉट नहीं",
        "Tidak ada snapshot asli untuk dipulihkan", "ไม่มีสแนปช็ตต้นฉบับให้คืน",
        "Geri alel yedek yok", "Không có ảnh gốc để khôi phục", "Aucune capture d'origine à restaurer",
        "Kein Original-Snapshot vorhanden", "无原始快照可恢复", "Sem snapshot original para restaurar",
        "Nessuno snapshot originale da ripristinare"],
    "restored_original": ["已恢复原始形象", "Original image restored", "Image d'origine restaurée",
        "원본 이미지를 복원했습니다", "تمت استعادة الصورة الأصلية", "已恢复原始形象",
        "Gambar asli dipulihkan", "กืนคืนภาพต้นฉบับแล้ว", "Özgün görsel geri yüklendi",
        "Đã khôi phục ảnh gốc", "Originalbild wiederhergestellt", "原始形象已恢复",
        "Imagen original restaurada", "Imagem original restaurada", "Immagine originale ripristinata"],
    "src_size_fail": ["源脸仅 {0}px,低于 256px 无法换脸,请换更清晰的图",
        "Source face is only {0}px — below 256px, cannot swap. Use a sharper image.",
        "元顔は {0}px のみ — 256px 未満のため換顔できません。鮮明な画像をご使用ください。",
        "소스 얼굴이 {0}px로 256px 미만이라 교체할 수 없습니다. 더 선명한 이미지를 사용하세요.",
        "وجه المصدر {0}px فقط — أقل من 256px، لا يمكن الاستبدال. استخدم صورة أوضح.",
        "स्रोत चेहरा केवल {0}px — 256px से कम, स्वैप नहीं हो सकता। तेज़ इमेज लें।",
        "Wajah sumber hanya {0}px — di bawah 256px, tidak bisa ditukar. Gunakan gambar lebih tajam.",
        "ใบหน้าต้นทางมีขนาดเพียง {0}px — ต่ำกว่า 256px จึงสลับไม่ได้ ใช้ภาพที่ชัดกว่า",
        "Kaynak yüz yalnızca {0}px — 256px altı, değiştirilemez. Daha keskin bir görsel kullanın.",
        "Khuôn mặt nguồn chỉ {0}px — dưới 256px nên không thể đổi. Hãy dùng ảnh sắc nét hơn.",
        "Visage source de seulement {0}px — sous 256px, échange impossible. Utilisez une image plus nette.",
        "Quellengesicht nur {0}px — unter 256px, kein Tausch möglich. Schärferes Bild verwenden.",
        "源脸仅 {0}px，低于 256px 无法换脸，请换更清晰的图",
        "Rosto de origem apenas {0}px — abaixo de 256px, não é possível trocar. Use uma imagem mais nítida.",
        "Volto sorgente di soli {0}px — sotto 256px, non si può scambiare. Usa un'immagine più nitida."],
    "src_size_warn": ["源脸 {0}×{1}(短边 {2}px)偏低,建议 ≥512px 以获得更稳的人脸细节",
        "Source face {0}×{1} (short side {2}px) is low; ≥512px gives steadier facial detail.",
        "元顔 {0}×{1}(短辺 {2}px)は低めです。顔细节が安定する 512px 以上推奨。",
        "소스 얼굴 {0}×{1}(짧은 변 {2}px)은 낮습니다. 512px 이상을 권장합니다.",
        "وجه المصدر {0}×{1} (الضلع القصير {2}px) منخفض؛ 512px أو أكثر يعطي تفاصيل أدق.",
        "स्रोत चेहरा {0}×{1}(छोटा किनारा {2}px) कम है; ≥512px बेहतर विवरण देता है।",
        "Wajah sumber {0}×{1} (sisi pendek {2}px) rendah; ≥512px memberi detail lebih stabil.",
        "ใบหน้าต้นทาง {0}×{1}(ด้านสั้น {2}px) ต่ำเกินไป แนะนำ ≥512px",
        "Kaynak yüz {0}×{1} (kısa kenar {2}px) düşük; ≥512px daha kararlı detay verir.",
        "Khuôn mặt nguồn {0}×{1} (cạnh ngắn {2}px) thấp; ≥512px cho chi tiết ổn định hơn.",
        "Visage source {0}×{1} (côté court {2}px) faible ; ≥512px donne un détail plus stable.",
        "Quellengesicht {0}×{1} (kurze Seite {2}px) ist klein; ≥512px liefert stabilere Details.",
        "源脸 {0}×{1}(短边 {2}px)偏低，建议 ≥512px 以获得更稳的人脸细节",
        "Rosto de origem {0}×{1} (lado curto {2}px) baixo; ≥512px dá detalhe mais estável.",
        "Volto sorgente {0}×{1} (lato corto {2}px) basso; ≥512px dà dettagli più stabili."],
    "src_size_ok": ["源脸 {0}×{1} 分辨率合格", "Source face {0}×{1} — resolution OK",
        "元顔 {0}×{1} — 解像度は十分です", "소스 얼굴 {0}×{1} — 해상도 충분",
        "وجه المصدر {0}×{1} — الدقة مناسبة", "स्रोत चेहरा {0}×{1} — रिज़ॉल्यूशन ठीक है",
        "Wajah sumber {0}×{1} — resolusi cukup", "ใบหน้าต้นทาง {0}×{1} — ความละเอียดเพียงพอ",
        "Kaynak yüz {0}×{1} — çözünürlük uygun", "Khuôn mặt nguồn {0}×{1} — độ phân giải ổn",
        "Visage source {0}×{1} — résolution correcte", "Quellengesicht {0}×{1} — Auflösung in Ordnung",
        "源脸 {0}×{1} 分辨率合格", "Rosto de origem {0}×{1} — resolução ok",
        "Volto sorgente {0}×{1} — risoluzione ok"],
    "update": ["更新", "Update", "更新", "업데이트", "تحديث", "अपडेट", "Perbarui", "อัปเดต",
               "Güncelle", "Cập nhật", "Mettre à jour", "Aktualisieren", "Actualizar",
               "Atualizar", "Aggiorna"],
    "update_failed_no_url": ["没有可用的下载地址", "No download URL available",
        "利用可能なダウンロード URL がありません", "사용 가능한 다운로드 URL이 없습니다",
        "لا يوجد عنوان تنزيل متاح", "कोई डाउनलोड URL उपलब्ध नहीं", "Tidak ada URL unduhan",
        "ไม่มี URL สำหรับดาวน์โหลด", "İndirilebilir URL yok", "Không có URL tải xuống",
        "Aucune URL de téléchargement", "Keine Download-URL", "Sin URL de descarga",
        "Sem URL de download", "Nessun URL di download"],
    "update_failed": ["更新失败:", "Update failed:", "更新に失敗しました:", "업데이트 실패:",
        "فشل التحديث:", "अपडेट विफल:", "Pembaruan gagal:", "อัปเดตล้มเหลว:", "Güncelleme başarısız:",
        "Cập nhật thất bại:", "Échec de la mise à jour :", "Update fehlgeschlagen:",
        "Actualización fallida:", "Falha na atualização:", "Aggiornamento fallito:"],
    "update_restart_q": ["已更新 {0} 个文件,立即重启生效吗?", "Updated {0} files. Restart now?",
        "{0} ファイルを更新しました。今すぐ再起動しますか?", "{0}개 파일을 업데이트했습니다. 지금 재시작할까요?",
        "تم تحديث {0} ملف. هل تريد إعادة التشغيل الآن؟", "{0} फ़ाइलें अपडेट हुईं। अभी पुनःआरंभ करें?",
        "{0} berkas diperbarui. Mulai ulang sekarang?", "อัปเดต {0} ไฟล์แล้ว ต้องการรีสตาร์ตตอนนี้ไหม",
        "{0} dosya güncellendi. Şimdi yeniden başlatılsın mı?", "Đã cập nhật {0} tệp. Khởi động lại ngay?",
        "{0} fichiers mis à jour. Redémarrer maintenant ?", "{0} Dateien aktualisiert. Jetzt neu starten?",
        "Se actualizaron {0} archivos. ¿Reiniciar ahora?", "{0} arquivos atualizados. Reiniciar agora?",
        "Aggiornati {0} file. Riavviare ora?"],
    "manual_templates": ["手动模板", "Manual templates", "手動テンプレート", "수동 템플릿",
        "قوالب يدوية", "मैनुअल टेम्पलेट", "Templat manual", "เทมเพลตด้วยมือ",
        "Manuel şablonlar", "Mẫu thủ công", "Modèles manuels", "Manuelle Vorlagen",
        "Plantillas manuales", "Modelos manuais", "Modelli manuali"],
    "no_key": ["无 Key", "No key", "キーなし", "키 없음", "بدون مفتاح", "कुंजी नहीं",
               "Tanpa kunci", "ไม่มีคีย์", "Anahtar yok", "Không có khóa", "Sans clé",
               "Kein Schlüssel", "Sin clave", "Sem chave", "Nessuna chiave"],
    "u_custom_ellipsis": ["自定义…", "Custom…", "カスタム…", "사용자 지정…", "مخصص…", "कस्टम…",
                          "Kustom…", "กำหนดเอง…", "Özel…", "Tùy chỉnh…", "Personnalisé…",
                          "Benutzerdefiniert…", "Personalizado…", "Personalizado…", "Personalizzato…"],
    # ── 状态 ──
    "u_pending": ["待开始", "Not started", "未開始", "시작 전", "لم يبدأ", "शुरू नहीं हुआ", "Belum mulai",
                  "ยังไม่เริ่ม", "Başlanmadı", "Chưa bắt đầu", "Non démarré", "Nicht begonnen",
                  "Sin iniciar", "Não iniciado", "Non iniziato"],
    "u_running": ["进行中", "In progress", "進行中", "진행 중", "قيد التنفيذ", "प्रगति पर", "Berjalan",
                  "กำลังดำเนินการ", "Devam ediyor", "Đang chạy", "En cours", "In Bearbeitung",
                  "En curso", "Em andamento", "In corso"],
    "u_done": ["已完成", "Done", "完了", "완료", "مكتمل", "पूर्ण", "Selesai", "เสร็จสิ้น", "Tamamlandı",
               "Đã xong", "Terminé", "Fertig", "Hecho", "Concluído", "Completato"],
    "u_failed": ["失败", "Failed", "失敗", "실패", "فشل", "विफल", "Gagal", "ล้มเหลว", "Başarısız",
                 "Thất bại", "Échec", "Fehlgeschlagen", "Fallido", "Falhou", "Fallito"],
    # ── 画幅 / 面孔文化 ──
    "u_ratio_16_9": ["16:9 · 横屏", "16:9 · Landscape", "16:9 · 横", "16:9 · 가로", "16:9 · أفقي",
                     "16:9 · क्षैतिज", "16:9 · Lanskap", "16:9 · แนวนอน", "16:9 · Yatay",
                     "16:9 · Ngang", "16:9 · Paysage", "16:9 · Querformat", "16:9 · Horizontal",
                     "16:9 · Horizontal", "16:9 · Orizzontale"],
    "u_ratio_9_16": ["9:16 · 竖屏", "9:16 · Portrait", "9:16 · 縦", "9:16 · 세로", "9:16 · عمودي",
                     "9:9 · लंबवत", "9:16 · Potret", "9:16 · แนวตั้ง", "9:16 · Dikey",
                     "9:16 · Dọc", "9:16 · Portrait", "9:16 · Hochformat", "9:16 · Vertical",
                     "9:16 · Vertical", "9:16 · Verticale"],
    "u_ratio_1_1": ["1:1 · 方形", "1:1 · Square", "1:1 · 正方形", "1:1 · 정사각형", "1:1 · مربع",
                    "1:1 · वर्गाकार", "1:1 · Persegi", "1:1 · สี่เหลี่ยมจัตุรัส", "1:1 · Kare",
                    "1:1 · Vuông", "1:1 · Carré", "1:1 · Quadrat", "1:1 · Cuadrado",
                    "1:1 · Quadrado", "1:1 · Quadrato"],
    "u_ratio_adaptive": ["自适应", "Adaptive", "自動調整", "자동", "تكيفي", "अनुकूली", "Adaptif",
                         "ปรับอัตราส่วน", "Uyarlanabilir", "Thích ứng", "Adaptatif", "Adaptiv",
                         "Adaptativo", "Adaptativo", "Adattivo"],
    "u_eth_east_asian": ["东亚", "East Asian", "東アジア", "동아시아", "شرق آسيا", "पूर्व एशियाई",
                         "Asia Timur", "เอเชียตะวันออก", "Doğu Asyalı", "Đông Á", "Est-asiatique",
                         "Ostasiatisch", "Este Asiático", "Ásia Oriental", "Est-asiatica"],
    "u_eth_middle_eastern": ["中东", "Middle Eastern", "中東", "중동", "الشرق الأوسط", "मध्य पूर्वी",
                             "Timur Tengah", "ตะวันออกกลาง", "Orta Doğu", "Trung Đông",
                             "Moyen-Orient", "Naher Osten", "Oriente Medio", "Oriente Médio",
                             "Medio Oriente"],
    "u_eth_western": ["西方", "Western", "欧米", "서양", "غربي", "पश्चिमी", "Barat", "ตะวันตก",
                      "Batı", "Phương Tây", "Occidental", "Westeuropäisch", "Occidental",
                      "Ocidental", "Occidentale"],
    "u_eth_south_asian": ["南亚", "South Asian", "南アジア", "남아시아", "جنوب آسيا", "दक्षिण एशियाई",
                          "Asia Selatan", "เอเชียใต้", "Güney Asyalı", "Nam Á", "Sud-asiatique",
                          "Südasiatisch", "Surasiático", "Sul-asiático", "Sudasiatica"],
    "u_eth_latin": ["拉美", "Latin American", "ラテンアメリカ", "라틴 아메리카", "أمريكا اللاتينية",
                    "लैटिन अमेरिकी", "Amerika Latin", "ลาตินอเมริกา", "Latin Amerika", "Mỹ Latinh",
                    "Latino-américain", "Lateinamerikanisch", "Latinoamericano",
                    "Latino-americano", "Latinoamericana"],
    "u_eth_african": ["非洲", "African", "アフリカ", "아프리카", "أفريقي", "अफ्रीकी", "Afrika",
                      "แอฟริกา", "Afrikalı", "Châu Phi", "Africain", "Afrikanisch", "Africano",
                      "Africano", "Africano"],
    "u_eth_mixed": ["混合", "Mixed", "ミックス", "혼합", "مختلط", "मिश्रित", "Campuran", "ผสม",
                    "Karma", "Hỗn hợp", "Mixte", "Gemischt", "Mixto", "Misto", "Misto"],
    # ── 审校 / 台账 ──
    "u_review_n": ["审校 {0} 项", "{0} review issues", "レビュー {0} 件", "검수 {0}건",
                   "{0} ملاحظات مراجعة", "{0} समीक्षा मुद्दे", "{0} masalah tinjauan",
                   "พบปัญหาตรวจ {0} รายการ", "{0} inceleme bulgusu", "{0} vấn đề kiểm tra",
                   "{0} points de révision", "{0} Prüfpunkte", "{0} incidencias de revisión",
                   "{0} questões de revisão", "{0} rilievi di revisione"],
    "u_ledger": ["状态台账", "State ledger", "状態台帳", "상태 장부", "سجل الحالة", "स्थिति बही",
                 "Catatan status", "บัญชีสถานะ", "Durum kaydı", "Sổ trạng thái",
                 "Registre d'état", "Zustandsprotokoll", "Registro de estado", "Registro de estado",
                 "Registro di stato"],
    "u_foreshadow": ["伏笔台账", "Foreshadow ledger", "伏線台帳", "복선 장부", "سجل الإشارات التمهيدية",
                     "संकेत बही", "Catatan foreshadow", "บัญชีการปูเดา", "İz örgütü", "Sổ dư bối",
                     "Registre des indices", "Vorspann-Register", "Registro de pistas",
                     "Registro de pistas", "Registro di anticipazioni"],
    # ── 变体 ──
    "u_variants": ["造型变体", "Style variants", "バリエーション", "스타일 변형", "تنوعات المظهر",
                   "वेरिएंट", "Varian gaya", "รูปแบบลักษณะ", "Varyantlar", "Biến thể phong cách",
                   "Variantes de style", "Stilvarianten", "Variantes de estilo",
                   "Variantes de estilo", "Varianti di stile"],
    # ── 分镜工作台 ──
    "u_task_list": ["视频任务列表", "Video task list", "動画タスク一覧", "비디오 작업 목록",
                    "قائمة مهام الفيديو", "वीडियो कार्य सूची", "Daftar tugas video",
                    "รายการงานวิดีโอ", "Video görev listesi", "Danh sách tác vụ video",
                    "Liste des tâches vidéo", "VideAufgabenliste", "Lista de tareas de vídeo",
                    "Lista de tarefas de vídeo", "Elenco attività video"],
    "u_video_prompt": ["视频提示词", "Video prompt", "動画プロンプト", "비디오 프롬프트",
                       "مطالبة الفيديو", "वीडियो प्रॉम्प्ट", "Prompt video", "พรอมต์วิดีโอ",
                       "Video istemi", "Prompt video", "Invite vidéo", "Video-Prompt",
                       "Aviso de vídeo", "Prompt de vídeo", "Prompt video"],
    "u_bound_refs": ["绑定参考图", "Bound references", "バインド参考図", "연결 참고 이미지",
                     "الصور المرجعية المرتبطة", "बंधी संदर्भ चित्र", "Referensi terikat",
                     "ภาพอ้างอิงที่ผูก", "Bağlı referanslar", "Ảnh tham chiếu đã liên kết",
                     "Références liées", "Gebundene Referenzen", "Referencias vinculadas",
                     "Referências vinculadas", "Riferimenti collegati"],
    "u_comic_style": ["画风", "Art style", "画風", "화풍", "النمط الفني", "कला शैली", "Gaya seni",
                      "สไตล์ศิลป์", "Sanat stili", "Phong cách nghệ thuật", "Style artistique",
                      "Künstlerischer Stil", "Estilo artístico", "Estilo artístico",
                      "Stile artistico"],
    "u_stitch_long": ["拼接长图", "Stitch long image", "長尺画像を結合", "긴 이미지 이어붙이기",
                      "دمج الصورة الطويلة", "लंबी छवि संयोजन", "Gabungkan gambar panjang",
                      "ต่อภาพยาว", "Uzun görseli birleştir", "Ghép ảnh dài", "Fusionner la bande dessinée",
                      "Langes Bild zusammenfügen", "Unir imagen larga", "Juntar imagem longa",
                      "Unisci immagine lunga"],
    "u_whole_chapter": ["整章处理", "Whole chapter", "章全体", "장 전체", "الفصل كاملاً", "पूरा अध्याय",
                        "Seluruh bab", "ทั้งบท", "Tüm bölüm", "Toàn chương", "Chapitre entier",
                        "Ganzes Kapitel", "Capítulo completo", "Capítulo inteiro", "Capitolo intero"],
    "u_ai_edit": ["✨ AI 修改", "✨ AI edit", "✨ AI 編集", "✨ AI 편집", "✨ تحرير بالذكاء",
                  "✨ AI संपादन", "✨ Edit AI", "✨ แก้ไขด้วย AI", "✨ AI düzenle", "✨ Sửa bằng AI",
                  "✨ Modification IA", "✨ KI-Bearbeitung", "✨ Edición IA", "✨ Edição IA",
                  "✨ Modifica IA"],
    "u_click_view": ["点击查看大图", "Click to view", "クリックで閲覧", "클릭하여 보기", "انقر للعرض",
                     "देखने के लिए क्लिक करें", "Klik untuk melihat", "คลิกเพื่อดู",
                     "Görüntülemek için tıkla", "Nhấn để xem", "Cliquez pour voir",
                     "Klicken zum Ansehen", "Haz clic para ver", "Clique para ver", "Clic per vedere"],
    "u_draft_btn": ["起草中", "Drafting", "下書き中", "초안 중", "جارٍ الصياغة", "प्रारूपण",
                    "Menyusun", "กำลังร่าง", "Taslaklanıyor", "Đang soạn", "Rédaction",
                    "Entwurf", "Redactando", "Redigindo", "Bozza"],
    # ── 工具页 ──
    "u_nav_face_swap": ["换脸", "Face swap", "顔入れ替え", "얼굴 교체", "تبديل الوجه", "चेहरा बदलें",
                        "Tukar wajah", "สลับใบหน้า", "Yüz değiştir", "Đổi mặt", "Échange de visage",
                        "Gesichtstausch", "Cambio de rostro", "Troca de rosto", "Scambio volto"],
    "u_nav_merger": ["合并", "Merger", "結合", "병합", "دمج", "विलय", "Gabung", "รวม", "Birleştir",
                     "Hợp nhất", "Fusion", "Zusammenführen", "Fusionar", "Mesclar", "Unisci"],
    "u_storage": ["存储", "Storage", "ストレージ", "저장소", "التخزين", "भंडारण", "Penyimpanan",
                  "พื้นที่จัดเก็บ", "Depolama", "Bộ nhớ", "Stockage", "Speicher", "Almacenamiento",
                  "Armazenamento", "Archiviazione"],
    "u_free_space": ["剩余可用", "Free space", "空き容量", "여유 공간", "المساحة الحرة", "खाली जगह",
                     "Ruang kosong", "พื้นที่ว่าง", "Boş alan", "Dung lượng trống", "Espace libre",
                     "Freier Speicher", "Espacio libre", "Espaço livre", "Spazio libero"],
    "u_path": ["数据目录", "Data directory", "データディレクトリ", "데이터 디렉터리",
               "دليل البيانات", "डेटा निर्देशिका", "Direktori data", "ไดเรกทอรีข้อมูล",
               "Veri dizini", "Thư mục dữ liệu", "Répertoire de données", "Datenverzeichnis",
               "Directorio de datos", "Diretório de dados", "Directory dati"],
    "u_auto_gen": ["正在自动生成首集内容…", "Generating first episode…", "第1集を自動生成中…",
                   "첫 화 자동 생성 중…", "جارٍ إنشاء الحلقة الأولى…", "पहला अध्याय स्वतः बना रहा है…",
                   "Sedang membuat episode pertama…", "กำลังสร้างตอนแรก…", "İlk bölüm oluşturuluyor…",
                   "Đang tạo tập đầu…", "Génération du premier épisode…", "Erste Folge wird erstellt…",
                   "Generando primer episodio…", "Gerando primeiro episódio…",
                   "Generazione del primo episodio…"],
}


def ui_lookup(lang: str, key: str) -> str | None:
    """查 UI 补充词典;未命中返回 None(交由主词典/回退处理)。"""
    row = S.get(key)
    if not row:
        return None
    try:
        return row[LANGS.index(lang)]
    except (ValueError, IndexError):
        return row[0]