# -*- coding: utf-8 -*-
"""UI 文案补充词典(第二层)。

`i18n.py` 的 Z 表是主词典;这里收**后续迭代中零散补进界面的文案**(原先直接写成中文字面量,
切语言时不会跟着变)。`i18n.tr()` 会先查主词典、再查本表,都没命中才回退到 key。

15 种语言全覆盖;新增条目时按 langs 顺序给出 15 个值,顺序不可错:
    zh en ja ko ar hi id th tr vi fr de es pt it
"""
from __future__ import annotations

LANGS = ["zh", "en", "ja", "ko", "ar", "hi", "id", "th", "tr", "vi", "fr", "de", "es", "pt", "it"]

# key: [zh, en, ja, ko, ar, hi, id, th, tr, vi, fr, de, es, pt, it]
S: dict[str, list[str]] = {
    # ── 通用动作 / 状态 ──
    "u_name": ["名称", "Name", "名前", "이름", "الاسم", "नाम", "Nama", "ชื่อ", "Ad", "Tên",
               "Nom", "Name", "Nombre", "Nome", "Nome"],
    "u_save": ["保存", "Save", "保存", "저장", "حفظ", "सहेजें", "Simpan", "บันทึก", "Kaydet",
               "Lưu", "Enregistrer", "Speichern", "Guardar", "Salvar", "Salva"],
    "u_cancel": ["取消", "Cancel", "キャンセル", "취소", "إلغاء", "रद्द", "Batal", "ยกเลิก",
                 "İptal", "Hủy", "Annuler", "Abbrechen", "Cancelar", "Cancelar", "Annulla"],
    "u_apply": ["应用", "Apply", "適用", "적용", "تطبيق", "लागू", "Terapkan", "ใช้", "Uygula",
                "Áp dụng", "Appliquer", "Anwenden", "Aplicar", "Aplicar", "Applica"],
    "u_delete": ["删除", "Delete", "削除", "삭제", "حذف", "हटाएँ", "Hapus", "ลบ", "Sil",
                 "Xóa", "Supprimer", "Löschen", "Eliminar", "Excluir", "Elimina"],
    "u_processing": ["处理中…", "Processing…", "処理中…", "처리 중…", "جارٍ المعالجة…", "प्रसंस्करण…",
                     "Memproses…", "กำลังประมวลผล…", "İşleniyor…", "Đang xử lý…", "Traitement…",
                     "Verarbeitung…", "Procesando…", "Processando…", "Elaborazione…"],
    "u_loading": ["加载中…", "Loading…", "読み込み中…", "불러오는 중…", "جارٍ التحميل…", "लोड हो रहा है…",
                  "Memuat…", "กำลังโหลด…", "Yükleniyor…", "Đang tải…", "Chargement…", "Wird geladen…",
                  "Cargando…", "Carregando…", "Caricamento…"],
    "u_close": ["关闭", "Close", "閉じる", "닫기", "إغلاق", "बंद", "Tutup", "ปิด", "Kapat", "Đóng",
                "Fermer", "Schließen", "Cerrar", "Fechar", "Chiudi"],
    "u_add": ["新增", "Add", "追加", "추가", "إضافة", "जोड़ें", "Tambah", "เพิ่ม", "Ekle", "Thêm",
              "Ajouter", "Hinzufügen", "Añadir", "Adicionar", "Aggiungi"],
    "u_edit": ["编辑", "Edit", "編集", "편집", "تحرير", "संपादित", "Edit", "แก้ไข", "Düzenle", "Sửa",
               "Modifier", "Bearbeiten", "Editar", "Editar", "Modifica"],
    "u_refresh": ["刷新", "Refresh", "更新", "새로고침", "تحديث", "ताज़ा", "Segarkan", "รีเฟรช",
                  "Yenile", "Làm mới", "Actualiser", "Aktualisieren", "Actualizar", "Atualizar",
                  "Aggiorna"],
    "u_download": ["下载", "Download", "ダウンロード", "다운로드", "تنزيل", "डाउनलोड", "Unduh",
                   "ดาวน์โหลด", "İndir", "Tải xuống", "Télécharger", "Herunterladen", "Descargar",
                   "Baixar", "Scarica"],
    "u_apply_all": ["全部应用", "Apply all", "すべて適用", "전체 적용", "تطبيق الكل", "सभी लागू करें",
                    "Terapkan semua", "ใช้ทั้งหมด", "Tümünü uygula", "Áp dụng tất cả",
                    "Tout appliquer", "Alle anwenden", "Aplicar todo", "Aplicar tudo", "Applica tutto"],
    "u_view_large": ["点击查看大图", "Click to view large", "クリックで拡大", "클릭하여 크게 보기",
                     "انقر لعرض أكبر", "बड़ा देखने के लिए क्लिक करें", "Klik untuk memperbesar",
                     "คลิกเพื่อดูขนาดใหญ่", "Büyük görüntülemek için tıkla", "Bấm để xem lớn",
                     "Cliquez pour agrandir", "Klicken für große Ansicht", "Clic para ver grande",
                     "Clique para ver grande", "Clic per vedere grande"],
    "u_drafting": ["起草中", "Drafting…", "下書き中…", "초안 작성 중…", "جارٍ الصياغة…", "प्रारूप बना रहे हैं…",
                   "Menyusun…", "กำลังร่าง…", "Taslaklanıyor…", "Đang soạn…", "Rédaction…",
                   "Entwurf wird erstellt…", "Redactando…", "Redigindo…", "Bozza in corso…"],
    # ── 项目设置 ──
    "u_genre": ["题材", "Genre", "ジャンル", "장르", "النوع", "शैली", "Genre", "ประเภท", "Tür",
                "Thể loại", "Genre", "Genre", "Género", "Gênero", "Genere"],
    "u_intro": ["简介", "Synopsis", "あらすじ", "소개", "ملخص", "सारांश", "Ringkasan", "เรื่องย่อ",
                "Özet", "Tóm tắt", "Résumé", "Kurzfassung", "Sinopsis", "Sinopse", "Sintesi"],
    "u_appearance": ["外貌", "Appearance", "外見", "외모", "المظهر", "रूप", "Penampilan", "รูปลักษณ์",
                     "Dış görünüş", "Ngoại hình", "Apparence", "Aussehen", "Apariencia", "Aparência",
                     "Aspetto"],
    "u_world": ["世界观", "Worldbuilding", "世界観", "세계관", "العالم", "दुनिया", "Dunia",
                "โลกทัศน์", "Dünya", "Thế giới", "Univers", "Welt", "Universo", "Universo",
                "Mondi"],
    "u_outline": ["总纲", "Outline", "大綱", "개요", "المخطط العام", "रूपरेखा", "Garis besar",
                  "โครงเรื่อง", "Ana hat", "Dàn ý", "Plan général", "Gliederung", "Esquema",
                  "Esboço", "Struttura"],
    "u_contract": ["故事合约", "Story contract", "物語契約", "이야기 계약", "عقد القصة", "कहानी का संक",
                   "Kontrak cerita", "สัญญาเรื่อง", "Hikâye sözleşmesi", "Hợp đồng truyện",
                   "Contrat narratif", "Storyvertrag", "Contrato de historia", "Contrato de história",
                   "Contratto narrativo"],
    "u_chapter_plan": ["章节计划", "Chapter plan", "章立て", "장차트 계획", "خطة الفصول", "अध्याय योजना",
                       "Rencana bab", "แผนบท", "Bölüm planı", "Kế hoạch chương", "Plan des chapitres",
                       "Kapitelplan", "Plan de capítulos", "Plano de capítulos", "Piano dei capitoli"],
    "u_main_characters": ["主要角色", "Main characters", "主要登場人物", "주요 인물", "الشخصيات الرئيسية",
                          "मुख्य पात्र", "Tokoh utama", "ตัวละครหลัก", "Ana kişiler", "Nhân vật chính",
                          "Personnages principaux", "Hauptfiguren", "Personajes principales",
                          "Personagens principais", "Personaggi principali"],
    "u_role": ["角色定位", "Role", "役割", "역할", "الدور", "भूमिका", "Peran", "บทบาท", "Rol", "Vai trò",
               "Rôle", "Rolle", "Papel", "Papel", "Ruolo"],
    "u_location": ["地点", "Location", "場所", "장소", "المكان", "स्थान", "Lokasi", "สถานที่",
                   "Konum", "Địa điểm", "Lieu", "Ort", "Ubicación", "Local", "Luogo"],
    "u_time": ["时间", "Time", "時間", "시간", "الوقت", "समय", "Waktu", "เวลา", "Zaman", "Thời gian",
               "Heure", "Zeit", "Hora", "Hora", "Tempo"],
    "u_description": ["描述", "Description", "説明", "설명", "الوصف", "विवरण", "Deskripsi",
                      "คำอธิบาย", "Açıklama", "Mô tả", "Description", "Beschreibung", "Descripción",
                      "Descrição", "Descrizione"],
    "u_service": ["服务", "Service", "サービス", "서비스", "الخدمة", "सेवा", "Layanan", "บริการ",
                  "Hizmet", "Dịch vụ", "Service", "Dienst", "Servicio", "Serviço", "Servizio"],
    "u_style": ["风格", "Style", "スタイル", "스타일", "النمط", "शैली", "Gaya", "สไตล์", "Stil",
                "Phong cách", "Style", "Stil", "Estilo", "Estilo", "Stile"],
    "u_creative_desc": ["创意描述", "Creative brief", "企画の意図", "창작 아이디어", "وصف الفكرة",
                        "रचनात्मक विवरण", "Butiran kreatif", "แนวคิดสร้างสรรค์",
                        "Yaratıcı açıklama", "Mô tả ý tưởng", "Description créative",
                        "Kreativbeschreibung", "Descripción creativa", "Descrição criativa",
                        "Descrizione creativa"],
    "u_whole_placeholder": ["一句话简介(可选)", "One-line synopsis (optional)",
                            "一言紹介文(任意)", "한 줄 소개(선택)",
                            "نبذة من سطر واحد(اختياري)", "एक पंक्ति सारांश(वैकल्पिक)",
                            "Ringkasan satu baris(opsional)", "สรุปบรรทัดเดียว(ไม่บังคับ)",
                            "Tek satır özet(isteğe bağlı)", "Tóm tắt một dòng(tùy chọn)",
                            "Synopsis en une ligne(facultatif)", "Einzeiler(optional)",
                            "Synopsis de una línea(opcional)", "Synopsis de uma linha(opcional)",
                            "Sintesi in una riga(opzionale)"],
    "status_marked": ["已标记为", "Marked as", "マークしました", "로 표시됨", "تم التعليم كـ",
                      "के रूप में चिह्नित", "Ditandai sebagai", "ทำเครื่องหมายว่า",
                      "Olarak işaretlendi", "Đã đánh dấu", "Marqué comme", "Markiert als",
                      "Marcado como", "Marcado como", "Contrassegnato come"],
    "no_snapshot_to_restore": ["没有可恢复的原始形象快照", "No original snapshot to restore",
        "Aucun instantané d'origine à restaurer", "復元すべき元のイメージがありません",
        "لا توجد لقطة أصلية للاستعادة", "को पुनर्स्थापित करने के लिए मूल स्नैपशॉट नहीं",
        "Tidak ada snapshot asli untuk dipulihkan", "ไม่มีสแนปช็ตต้นฉบับให้คืน",
        "Geri alel yedek yok", "Không có ảnh gốc để khôi phục", "Aucune capture d'origine à restaurer",
        "Kein Original-Snapshot vorhanden", "无原始快照可恢复", "Sem snapshot original para restaurar",
        "Nessuno snapshot originale da ripristinare"],
    "restored_original": ["已恢复原始形象", "Original image restored", "Image d'origine restaurée",
        "원본 이미지를 복원했습니다", "تمت استعادة الصورة الأصلية", "已恢复原始形象",
        "Gambar asli dipulihkan", "กืนคืนภาพต้นฉบับแล้ว", "Özgün görsel geri yüklendi",
        "Đã khôi phục ảnh gốc", "Originalbild wiederhergestellt", "原始形象已恢复",
        "Imagen original restaurada", "Imagem original restaurada", "Immagine originale ripristinata"],
    "src_size_fail": ["源脸仅 {0}px,低于 256px 无法换脸,请换更清晰的图",
        "Source face is only {0}px — below 256px, cannot swap. Use a sharper image.",
        "元顔は {0}px のみ — 256px 未満のため換顔できません。鮮明な画像をご使用ください。",
        "소스 얼굴이 {0}px로 256px 미만이라 교체할 수 없습니다. 더 선명한 이미지를 사용하세요.",
        "وجه المصدر {0}px فقط — أقل من 256px، لا يمكن الاستبدال. استخدم صورة أوضح.",
        "स्रोत चेहरा केवल {0}px — 256px से कम, स्वैप नहीं हो सकता। तेज़ इमेज लें।",
        "Wajah sumber hanya {0}px — di bawah 256px, tidak bisa ditukar. Gunakan gambar lebih tajam.",
        "ใบหน้าต้นทางมีขนาดเพียง {0}px — ต่ำกว่า 256px จึงสลับไม่ได้ ใช้ภาพที่ชัดกว่า",
        "Kaynak yüz yalnızca {0}px — 256px altı, değiştirilemez. Daha keskin bir görsel kullanın.",
        "Khuôn mặt nguồn chỉ {0}px — dưới 256px nên không thể đổi. Hãy dùng ảnh sắc nét hơn.",
        "Visage source de seulement {0}px — sous 256px, échange impossible. Utilisez une image plus nette.",
        "Quellengesicht nur {0}px — unter 256px, kein Tausch möglich. Schärferes Bild verwenden.",
        "源脸仅 {0}px，低于 256px 无法换脸，请换更清晰的图",
        "Rosto de origem apenas {0}px — abaixo de 256px, não é possível trocar. Use uma imagem mais nítida.",
        "Volto sorgente di soli {0}px — sotto 256px, non si può scambiare. Usa un'immagine più nitida."],
    "src_size_warn": ["源脸 {0}×{1}(短边 {2}px)偏低,建议 ≥512px 以获得更稳的人脸细节",
        "Source face {0}×{1} (short side {2}px) is low; ≥512px gives steadier facial detail.",
        "元顔 {0}×{1}(短辺 {2}px)は低めです。顔细节が安定する 512px 以上推奨。",
        "소스 얼굴 {0}×{1}(짧은 변 {2}px)은 낮습니다. 512px 이상을 권장합니다.",
        "وجه المصدر {0}×{1} (الضلع القصير {2}px) منخفض؛ 512px أو أكثر يعطي تفاصيل أدق.",
        "स्रोत चेहरा {0}×{1}(छोटा किनारा {2}px) कम है; ≥512px बेहतर विवरण देता है।",
        "Wajah sumber {0}×{1} (sisi pendek {2}px) rendah; ≥512px memberi detail lebih stabil.",
        "ใบหน้าต้นทาง {0}×{1}(ด้านสั้น {2}px) ต่ำเกินไป แนะนำ ≥512px",
        "Kaynak yüz {0}×{1} (kısa kenar {2}px) düşük; ≥512px daha kararlı detay verir.",
        "Khuôn mặt nguồn {0}×{1} (cạnh ngắn {2}px) thấp; ≥512px cho chi tiết ổn định hơn.",
        "Visage source {0}×{1} (côté court {2}px) faible ; ≥512px donne un détail plus stable.",
        "Quellengesicht {0}×{1} (kurze Seite {2}px) ist klein; ≥512px liefert stabilere Details.",
        "源脸 {0}×{1}(短边 {2}px)偏低，建议 ≥512px 以获得更稳的人脸细节",
        "Rosto de origem {0}×{1} (lado curto {2}px) baixo; ≥512px dá detalhe mais estável.",
        "Volto sorgente {0}×{1} (lato corto {2}px) basso; ≥512px dà dettagli più stabili."],
    "src_size_ok": ["源脸 {0}×{1} 分辨率合格", "Source face {0}×{1} — resolution OK",
        "元顔 {0}×{1} — 解像度は十分です", "소스 얼굴 {0}×{1} — 해상도 충분",
        "وجه المصدر {0}×{1} — الدقة مناسبة", "स्रोत चेहरा {0}×{1} — रिज़ॉल्यूशन ठीक है",
        "Wajah sumber {0}×{1} — resolusi cukup", "ใบหน้าต้นทาง {0}×{1} — ความละเอียดเพียงพอ",
        "Kaynak yüz {0}×{1} — çözünürlük uygun", "Khuôn mặt nguồn {0}×{1} — độ phân giải ổn",
        "Visage source {0}×{1} — résolution correcte", "Quellengesicht {0}×{1} — Auflösung in Ordnung",
        "源脸 {0}×{1} 分辨率合格", "Rosto de origem {0}×{1} — resolução ok",
        "Volto sorgente {0}×{1} — risoluzione ok"],
    "update": ["更新", "Update", "更新", "업데이트", "تحديث", "अपडेट", "Perbarui", "อัปเดต",
               "Güncelle", "Cập nhật", "Mettre à jour", "Aktualisieren", "Actualizar",
               "Atualizar", "Aggiorna"],
    "update_failed_no_url": ["没有可用的下载地址", "No download URL available",
        "利用可能なダウンロード URL がありません", "사용 가능한 다운로드 URL이 없습니다",
        "لا يوجد عنوان تنزيل متاح", "कोई डाउनलोड URL उपलब्ध नहीं", "Tidak ada URL unduhan",
        "ไม่มี URL สำหรับดาวน์โหลด", "İndirilebilir URL yok", "Không có URL tải xuống",
        "Aucune URL de téléchargement", "Keine Download-URL", "Sin URL de descarga",
        "Sem URL de download", "Nessun URL di download"],
    "update_failed": ["更新失败:", "Update failed:", "更新に失敗しました:", "업데이트 실패:",
        "فشل التحديث:", "अपडेट विफल:", "Pembaruan gagal:", "อัปเดตล้มเหลว:", "Güncelleme başarısız:",
        "Cập nhật thất bại:", "Échec de la mise à jour :", "Update fehlgeschlagen:",
        "Actualización fallida:", "Falha na atualização:", "Aggiornamento fallito:"],
    "update_restart_q": ["已更新 {0} 个文件,立即重启生效吗?", "Updated {0} files. Restart now?",
        "{0} ファイルを更新しました。今すぐ再起動しますか?", "{0}개 파일을 업데이트했습니다. 지금 재시작할까요?",
        "تم تحديث {0} ملف. هل تريد إعادة التشغيل الآن؟", "{0} फ़ाइलें अपडेट हुईं। अभी पुनःआरंभ करें?",
        "{0} berkas diperbarui. Mulai ulang sekarang?", "อัปเดต {0} ไฟล์แล้ว ต้องการรีสตาร์ตตอนนี้ไหม",
        "{0} dosya güncellendi. Şimdi yeniden başlatılsın mı?", "Đã cập nhật {0} tệp. Khởi động lại ngay?",
        "{0} fichiers mis à jour. Redémarrer maintenant ?", "{0} Dateien aktualisiert. Jetzt neu starten?",
        "Se actualizaron {0} archivos. ¿Reiniciar ahora?", "{0} arquivos atualizados. Reiniciar agora?",
        "Aggiornati {0} file. Riavviare ora?"],
    "manual_templates": ["手动模板", "Manual templates", "手動テンプレート", "수동 템플릿",
        "قوالب يدوية", "मैनुअल टेम्पलेट", "Templat manual", "เทมเพลตด้วยมือ",
        "Manuel şablonlar", "Mẫu thủ công", "Modèles manuels", "Manuelle Vorlagen",
        "Plantillas manuales", "Modelos manuais", "Modelli manuali"],
    "no_key": ["无 Key", "No key", "キーなし", "키 없음", "بدون مفتاح", "कुंजी नहीं",
               "Tanpa kunci", "ไม่มีคีย์", "Anahtar yok", "Không có khóa", "Sans clé",
               "Kein Schlüssel", "Sin clave", "Sem chave", "Nessuna chiave"],
    "svc_empty": ["还没有配置", "No configuration yet", "まだ設定がありません", "아직 설정이 없습니다",
        "لا يوجد إعداد بعد", "अभी कोई कॉन्फ़िगरेशन नहीं", "Belum ada konfigurasi",
        "ยังไม่มีการตั้งค่า", "Henüz yapılandırma yok", "Chưa cấu hình",
        "Aucune configuration", "Noch keine Konfiguration", "Sin configuración",
        "Sem configuração", "Nessuna configurazione"],
    "toggle_enabled": ["启用 / 停用该配置", "Enable / disable this configuration",
        "この設定を有効 / 無効にする", "이 설정 활성화 / 비활성화", "تفعيل / تعطيل هذا الإعداد",
        "इस कॉन्फ़िगरेशन को सक्षम / अक्षम करें", "Aktifkan / nonaktifkan konfigurasi ini",
        "เปิด / ปิดการตั้งค่านี้", "Bu yapılandırmayı etkinleştir / devre dışı bırak",
        "Bật / tắt cấu hình này", "Activer / désactiver cette configuration",
        "Diese Konfiguration aktivieren / deaktivieren", "Activar / desactivar esta configuración",
        "Ativar / desativar esta configuração", "Attiva / disattiva questa configurazione"],
    "click_set_default_model": ["点击设为该配置的默认模型", "Click to set as this config's default model",
        "クリックで既定モデルに設定", "클릭해 이 설정의 기본 모델로 지정", "انقر لتعيينه كنموذج افتراضي",
        "इस कॉन्फ़िगरेशन का डिफ़ॉल्ट मॉडल बनाएँ", "Klik untuk dijadikan model bawaan",
        "คลิกเพื่อตั้งเป็นโมเดลเริ่มต้น", "Tıklayarak varsayılan model yap",
        "Nhấn để đặt làm mô hình mặc định", "Cliquez pour définir le modèle par défaut",
        "Klicken, um als Standardmodell festzulegen", "Haz clic para设为模型 predeterminado",
        "Clique para definir como modelo padrão", "Clic per impostare come modello predefinito"],
    "is_default_model": ["当前默认模型", "Current default model", "現在の既定モデル", "현재 기본 모델",
        "النموذج الافتراضي الحالي", "वर्तमान डिफ़ॉल्ट मॉडल", "Model bawaan saat ini",
        "โมเดลเริ่มต้นปัจจุบัน", "Geçerli varsayılan model", "Mô hình mặc định hiện tại",
        "Modèle par défaut actuel", "Aktuelles Standardmodell", "Modelo predeterminado actual",
        "Modelo padrão atual", "Modello predefinito attuale"],
    "no_models_yet": ["尚未填写模型名", "No model set yet", "モデル未設定", "모델이 아직 없습니다",
        "Belum ada model", "अभी तक कोई मॉडल नहीं", "Belum ada model", "ยังไม่ได้ตั้งค่าโมเดล",
        "Henüz model yok", "Chưa có mô hình", "Aucun modèle défini", "Noch kein Modell gesetzt",
        "Aún sin modelo", "Ainda sem modelo", "Nessun modello impostato"],
    "test_ok": ["测试通过", "Test passed", "テスト成功", "테스트 통과", "نجح الاختبار", "परीक्षण उत्तीर्ण",
        "Uji berhasil", "ทดสอบผ่าน", "Test başarılı", "Kiểm tra thành công", "Test réussi",
        "Test bestanden", "Prueba superada", "Teste aprovado", "Test superato"],
    "test_fail": ["测试失败", "Test failed", "テスト失敗", "테스트 실패", "فشل الاختبار", "परीक्षण विफल",
        "Uji gagal", "ทดสอบล้มเหลว", "Test başarısız", "Kiểm tra thất bại", "Échec du test",
        "Test fehlgeschlagen", "Prueba fallida", "Teste falhou", "Test fallito"],
    "confirm_delete_service": ["确定删除配置「{0}」?", "Delete configuration \"{0}\"?",
        "設定「{0}」を削除しますか?", "설정 \"{0}\" 을(를) 삭제할까요?", "حذف الإعداد \"{0}\"؟",
        "कॉन्फ़िगरेशन \"{0}\" हटाएँ?", "Hapus konfigurasi \"{0}\"?",
        "ลบการตั้งค่า \"{0}\"?", "\"{0}\" yapılandırması silinsin mi?", "Xóa cấu hình \"{0}\"?",
        "Supprimer la configuration « {0} » ?", "Konfiguration \"{0}\" löschen?",
        "¿Eliminar la configuración \"{0}\"?", "Excluir a configuração \"{0}\"?",
        "Eliminare la configurazione \"{0}\"?"],
    # ── 换脸三段式向导 ──
    "face_swap_hint": ["① 选源人脸 → ② 选角色模板图 → ③ 批量换脸并应用回角色形象。",
        "① Pick a source face → ② pick character templates → ③ batch-swap and apply back.",
        "① 源顔を選ぶ → ② 角色的テンプレート図を選ぶ → ③ 一括換顔して角色に書き戻す。",
        "① 소스얼굴 선택 → ② 캐릭터 템플릿 선택 → ③ 일괄 교체 후 캐릭터에 반영.",
        "① اختر وجه المصدر ← ② اختر قوالب الشخصية ← ③ بدّل دفعةً واحدة وطبّق على الشخصية.",
        "① स्रोत चेहरा चुनें → ② किरदार टेम्पलेट चुनें → ③ बैच में बदलें और लागू करें।",
        "① Pilih wajah sumber → ② pilih template karakter → ③ tukar massal dan terapkan.",
        "① เลือกใบหน้าต้นทาง → ② เลือกภาพต้นแบบตัวละคร → ③ สลับทั้งชุดและนำไปใช้",
        "① Kaynak yüz seçin → ② karakter şablonlarını seçin → ③ toplu değiştirip uygula.",
        "① Chọn khuôn mặt nguồn → ② chọn ảnh mẫu nhân vật → ③ đổi hàng loạt và áp dụng.",
        "① 选源人脸 → ② 选角色模板图 → ③ 批量换脸并应用回角色形象。",
        "① Quellengesicht wählen → ② Charakter-Vorlagen wählen → ③ Stapelaustausch anwenden.",
        "① 选源人脸 → ② 选角色模板图 → ③ 批量换脸并应用回角色形象。",
        "① Escolha o rosto de origem → ② escolha modelos → ③ troque em lote e aplique.",
        "① Scegli il volto di origine → ② scegli i modelli → ③ scambia in blocco e applica."],
    "engine": ["引擎", "Engine", "エンジン", "엔진", "المحرك", "इंजन", "Mesin", "เอนจิน",
               "Motor", "Động cơ", "Moteur", "Motor", "Motor", "Motor", "Motore"],
    "engine_tip": ["换脸服务与图片模型都会列出;图片模型可用于风格化重绘。",
        "Lists face-swap services and image models; image models can restyle the result.",
        "換顔サービスと画像モデルの両方を表示。画像モデルはスタイル調整に使えます。",
        "얼굴 교체 서비스와 이미지 모델이 모두 표시됩니다.",
        "تظهر كل من خدمات تبديل الوجه ونماذج الصور.",
        "चेहरा बदलने की सेवाएँ और चित्र मॉडल दोनों दिखते हैं।",
        "Baik layanan tukar wajah maupun model gambar ditampilkan.",
        "แสดงทั้งบริการเปลี่ยนใบหน้าและโมเดลภาพ",
        "Hem yüz değiştirme servisleri hem görsel modelleri listelenir.",
        "Liệt kê dịch vụ đổi mặt và mô hình ảnh.",
        "Liste les services d'échange de visage et les modèles d'image.",
        "Gesichtstausch-Dienste und Bildmodelle werden aufgelistet.",
        "列出换脸服务与图像模型。",
        "Lista trocas de rosto e modelos de imagem.",
        "Elenca i servizi di scambio volto e i modelli immagine."],
    "faceswap_service": ["换脸", "Face swap", "換顔", "얼굴 교체", "تبديل الوجه", "चेहरा बदलें",
                         "Tukar wajah", "เปลี่ยนใบหน้า", "Yüz değiştirme", "Đổi mặt",
                         "Échange de visage", "Gesichtstausch", "Cambio de rostro",
                         "Troca de rosto", "Scambio volto"],
    "image_service": ["图片模型", "Image model", "画像モデル", "이미지 모델", "نموذج صور",
                      "चित्र मॉडल", "Model gambar", "โมเดลภาพ", "Görsel modeli", "Mô hình ảnh",
                      "Modèle d'image", "Bildmodell", "Modelo de imagen", "Modelo de imagem",
                      "Modello immagine"],
    "local_service_not_configured": ["未配置换脸服务", "No face-swap service configured",
        "換顔サービス未設定", "얼굴 교체 서비스 미설정", "لم يتم إعداد خدمة تبديل الوجه",
        "चेहरा बदलने की सेवा कॉन्फ़िगर नहीं", "Belum ada layanan tukar wajah",
        "ยังไม่ได้ตั้งค่าบริการเปลี่ยนใบหน้า", "Yüz değiştirme servisi yok",
        "Chưa cấu hình dịch vụ đổi mặt", "Aucun service d'échange de visage",
        "Kein Gesichtstausch-Dienst konfiguriert", "未配置换脸服务",
        "Nenhum serviço de troca de rosto", "Nessun servizio di scambio volto"],
    "style_prompt_ph": ["补充提示词(可选),会拼在风格描述之后",
        "Extra prompt (optional), appended after the style phrase",
        "追加プロンプト(任意)——スタイル記述の後ろに連結されます",
        "추가 프롬프트(선택), 스타일 설명 뒤에 붙습니다",
        "موجّه إضافي(اختياري) يُضاف بعد وصف الأسلوب",
        "अतिरिक्त प्रॉम्प्ट(वैकल्पिक), शैली विवरण के बाद जोड़ा जाता है",
        "Prompt tambahan (opsional), ditambahkan setelah deskripsi gaya",
        "พรอมต์เสริม(ไม่บังคับ) ต่อท้ายคำอธิบายสไตล์",
        "Ek ipucu (isteğe bağlı), stil açıklamasından sonra eklenir",
        "Prompt bổ sung (tùy chọn), nối sau mô tả phong cách",
        "Invite supplémentaire (facultatif), ajouté après la description de style",
        "Zusätzlicher Prompt (optional), nach der Stilbeschreibung angehängt",
        "补充提示词(可选),会拼在风格描述之后",
        "Prompt extra (opcional), anexado após a descrição de estilo",
        "Prompt aggiuntivo (faczionale), aggiunto dopo la descrizione dello stile"],
    "step1_source": ["源人脸", "Source face", "元顔", "소스얼굴", "وجه المصدر", "स्रोत चेहरा",
        "Wajah sumber", "ใบหน้าต้นทาง", "Kaynak yüz", "Khuôn mặt nguồn", "Visage source",
        "Quellengesicht", "Rostro de origen", "Rosto de origem", "Volto di origine"],
    "step2_template": ["角色模板图", "Character templates", "角色的テンプレ画像", "캐릭터 템플릿",
        "قوالب الشخصية", "किरदार टेम्पलेट", "Template karakter", "ภาพต้นแบบตัวละคร",
        "Karakter şablonları", "Ảnh mẫu nhân vật", "Modèles de personnage",
        "Charaktervorlagen", "Plantillas de personaje", "Modelos de personagem",
        "Modelli personaggio"],
    "step3_result": ["结果", "Result", "結果", "결과", "النتيجة", "परिणाम", "Hasil", "ผลลัพธ์",
        "Sonuç", "Kết quả", "Résultat", "Ergebnis", "Resultado", "Resultado", "Risultato"],
    "step1_source_hint": ["换脸质量主要取决于源人脸:正脸、无遮挡、分辨率越高越好。",
        "Swap quality depends mostly on the source face: front-facing, unobstructed, high-res.",
        "換顔品質は主に元顔で決まります。正面・遮蔽なし・高解像度が理想。",
        "교체 품질은 소스얼굴에 크게 좌우됩니다. 정면·무방해·고해상도가 좋습니다.",
        "تعتمد جودة التبديل غالبًا على وجه المصدر.",
        "गुणवत्ता मुख्यतः स्रोत चेहरे पर निर्भर।",
        "Kualitas tukar wajah terutama bergantung pada wajah sumber.",
        "คุณภาพขึ้นกับใบหน้าต้นทางเป็นหลัก",
        "Değiştirme kalitesi büyük ölçüde kaynak yüze bağlıdır.",
        "Chất lượng đổi mặt phụ thuộc vào khuôn mặt nguồn.",
        "La qualité dépend surtout du visage source.",
        "Die Tauschqualität hängt vor allem vom Quellengesicht ab.",
        "换脸质量主要取决于源人脸",
        "A qualidade depende principalmente do rosto de origem.",
        "La qualità dipende soprattutto dal volto di origine."],
    "pick_source_file": ["选择源脸照片", "Pick source face", "元顔を選ぶ", "소스얼굴 선택",
        "اختر وجه المصدر", "स्रोत चेहरा चुनें", "Pilih wajah sumber", "เลือกใบหน้าต้นทาง",
        "Kaynak yüz seç", "Chọn khuôn mặt nguồn", "Choisir le visage source",
        "Quellengesicht wählen", "选择源脸照片", "Escolher rosto de origem", "Scegli volto di origine"],
    "paste_from_clipboard": ["从剪贴板粘贴", "Paste from clipboard", "クリップボードから貼付",
        "클립보드에서 붙여넣기", "لصق من الحافظة", "क्लिपबोर्ड से चिपकाएँ", "Tempel dari papan klip",
        "วางจากคลิปบอร์ด", "Panodan yapıştır", "Dán từ bảng nhớ tạm",
        "Coller depuis le presse-papiers", "Aus Zwischenablage einfügen", "从剪贴板粘贴",
        "Colar da área de transferência", "Incolla dagli appunti"],
    "source_url_ph": ["或粘贴图片 URL", "or paste an image URL", "または画像 URL",
        "또는 이미지 URL", "أو الصق رابط صورة", "या चित्र URL चिपकाएँ", "atau tempel URL gambar",
        "หรือวาง URL รูปภาพ", "veya resim URL'si yapıştırın", "hoặc dán URL ảnh",
        "ou collez l'URL d'une image", "oder Bild-URL einfügen", "或粘贴图片 URL",
        "ou cole a URL da imagem", "o incolla un URL di immagine"],
    "use_url": ["取回", "Fetch", "取得", "가져오기", "جلب", "प्राप्त करें", "Ambil", "ดึง",
        "Getir", "Lấy", "Récupérer", "Abrufen", "取回", "Buscar", "Recupera"],
    "no_source": ["未选择源人脸", "No source face", "元顔未選択", "소스얼굴 미선택",
        "لم يتم اختيار وجه المصدر", "स्रोत चेहरा चयनित नहीं", "Belum pilih wajah sumber",
        "ยังไม่ได้เลือกใบหน้าต้นทาง", "Kaynak yüz seçilmedi", "Chưa chọn khuôn mặt nguồn",
        "Aucun visage source", "Kein Quellengesicht", "未选择源人脸",
        "Nenhum rosto de origem", "Nessun volto di origine"],
    "clipboard_empty": ["剪贴板为空", "Clipboard is empty", "クリップボードは空です",
        "클립보드가 비어 있습니다", "الحافظة فارغة", "क्लिपबोर्ड खाली है", "Papan klip kosong",
        "คลิปบอร์ดว่าง", "Pano boş", "Bảng nhớ tạm trống", "Presse-papiers vide",
        "Zwischenablage leer", "剪贴板为空", "Área de transferência vazia",
        "Appunti vuoti"],
    "source_not_found": ["文件不存在", "File not found", "ファイルがありません", "파일 없음",
        "الملف غير موجود", "फ़ाइल नहीं मिली", "Berkas tidak ditemukan", "ไม่พบไฟล์",
        "Dosya bulunamadı", "Không tìm thấy tệp", "Fichier introuvable",
        "Datei nicht gefunden", "文件不存在", "Arquivo não encontrado", "File non trovato"],
    "source_url_failed": ["取回失败:", "Fetch failed:", "取得に失敗しました:", "가져오기 실패:",
        "فشل الجلب:", "प्राप्त करने में विफल:", "Gagal mengambil:", "ดึงไม่สำเร็จ:",
        "Alınamadı:", "Không lấy được:", "Échec de récupération:", "Abruf fehlgeschlagen:",
        "取回失败:", "Falha ao buscar:", "Recupero non riuscito"],
    "step2_template_hint": ["载入该角色的基础形象与全部造型变体;也可追加本地图片。",
        "Loads the character's base image and every style variant; local files can be added too.",
        "その角色的基本形象とすべてのバリエーションをロード。ローカル画像の追加も可能。",
        "해당 캐릭터의 기본 이미지와 모든 스타일 변형을 불러옵니다.",
        "يحمّل صورة الشخصية الأساسية وجميع الأنماط.",
        "किरदार की मूल छवि और सभी शैली रूप लोड करता है।",
        "Memuat gambar dasar dan semua varian gaya.",
        "โหลดภาพต้นฉบับและทุกสไตล์ของตัวละคร",
        "Karakterin temel görselini ve tüm stil varyantlarını yükler.",
        "Tải ảnh gốc và mọi biến thể phong cách của nhân vật.",
        "Charge l'image de base et toutes les variantes de style.",
        "Lädt Basisbild und alle Stilvarianten.",
        "载入该角色的基础形象与全部造型变体",
        "Carrega a imagem base e todas as variantes de estilo.",
        "Carica l'immagine base e tutte le varianti di stile."],
    "pick_character_first": ["先在上方选择角色", "Pick a character above", "先にキャラクターを選択",
        "먼저 위에서 캐릭터를 선택하세요", "اختر شخصية من الأعلى", "पहले ऊपर एक किरदार चुनें",
        "Pilih karakter di atas", "เลือกตัวละครด้านบนก่อน", "Önce bir karakter seçin",
        "Hãy chọn nhân vật ở trên", "Choisissez d'abord un personnage",
        "Zuerst eine Figur wählen", "先在上方选择角色", "Escolha um personagem acima",
        "Scegli prima un personaggio"],
    "add_local_files": ["＋ 本地图片", "＋ Local images", "＋ ローカル画像", "＋ 로컬 이미지",
        "＋ صور محلية", "＋ स्थानीय छवियाँ", "＋ Gambar lokal", "＋ รูปภาพในเครื่อง",
        "＋ Yerel görseller", "＋ Ảnh cục bộ", "＋ Images locales", "＋ Lokale Bilder",
        "＋ 本地图片", "＋ Imagens locais", "＋ Immagini locali"],
    "add_local_files_tip": ["在角色模板之外追加任意本地图片作为换脸目标。",
        "Add any local image as an extra swap target.",
        "キャラクターのテンプレートに加えて任意のローカル画像を追加します。",
        "캐릭터 템플릿 외에 임의의 로컬 이미지를 추가합니다.",
        "أضف أي صورة محلية كهدف إضافي.",
        "बिना चरित्र टेम्पलेट के किसी भी स्थानीय छवि को जोड़ें।",
        "Tambah gambar lokal apa pun sebagai target.",
        "เพิ่มรูปภาพในเครื่องใดก็ได้เป็นเป้าหมาย",
        "Herhangi bir yerel görseli hedef olarak ekleyin.",
        "Thêm bất kỳ ảnh cục bộ nào làm mục tiêu.",
        "Ajoutez n'importe quelle image locale.",
        "Fügen Sie beliebige lokale Bilder hinzu.",
        "追加本地图片", "Adicione qualquer imagem local.", "Aggiungi qualsiasi immagine locale."],
    "clear_all": ["清空", "Clear", "クリア", "지우기", "مسح", "साफ़ करें", "Bersihkan", "ล้าง",
        "Temizle", "Xóa hết", "Tout effacer", "Leeren", "清空", "Limpar", "Svuota"],
    "redraw_this": ["重绘这一张", "Redraw this one", "この1枚だけ再描画", "이 장만 다시 그리기",
        "إعادة رسم هذه فقط", "इसे ही दोबारा बनाएँ", "Gambar ulang yang ini saja",
        "วาดใหม่เฉพาะใบนี้", "Yalnızca bunu yeniden çiz", "Vẽ lại riêng ảnh này",
        "Redessiner celle-ci", "Nur dieses neu zeichnen", "重绘这一张",
        "Redesenhar apenas esta", "Ridisegna solo questa"],
    "remove_from_list": ["从列表移除", "Remove from list", "リストから削除", "목록에서 제거",
        "إزالة من القائمة", "सूची से हटाएँ", "Hapus dari daftar", "นำออกจากรายการ",
        "Listeden çıkar", "Xóa khỏi danh sách", "Retirer de la liste", "Aus der Liste entfernen",
        "从列表移除", "Remover da lista", "Rimuovi dall'elenco"],
    "swapped": ["已换脸", "Swapped", "換顔済み", "교체 완료", "تم التبديل", "बदला गया",
        "Tukar wajah", "เปลี่ยนแล้ว", "Değiştirildi", "Đã đổi", "Échangé", "Getauscht",
        "Cambiado", "Trocado", "Scambiato"],
    "no_result_yet": ["还没有结果", "No result yet", "結果なし", "아직 결과 없음", "لا توجد نتيجة بعد",
        "अभी कोई परिणाम नहीं", "Belum ada hasil", "ยังไม่มีผลลัพธ์", "Henüz sonuç yok",
        "Chưa có kết quả", "Aucun résultat", "Noch kein Ergebnis", "还没有结果",
        "Sem resultado ainda", "Nessun risultato"],
    "start_swap": ["开始换脸", "Start", "換顔開始", "교체 시작", "بدء التبديل", "बदलना शुरू करें",
        "Mulai tukar wajah", "เริ่มการเปลี่ยนใบหน้า", "Değiştirmeyi başlat", "Bắt đầu đổi mặt",
        "Démarrer l'échange", "Austausch starten", "开始换脸", "Iniciar troca",
        "Avvia scambio"],
    "download_all": ["全部下载", "Download all", "すべてダウンロード", "전체 다운로드",
        "تنزيل الكل", "सभी डाउनलोड करें", "Unduh semua", "ดาวน์โหลดทั้งหมด",
        "Tümünü indir", "Tải tất cả", "Tout télécharger", "Alle herunterladen",
        "全部下载", "Baixar tudo", "Scarica tutto"],
    "apply_to_character": ["应用到角色形象", "Apply to character", "角色形象的適用", "캐릭터 이미지에 적용",
        "تطبيق على صورة الشخصية", "किरदार छवि पर लागू करें", "Terapkan ke gambar karakter",
        "ใช้กับภาพตัวละคร", "Karakter görseline uygula", "Áp dụng vào ảnh nhân vật",
        "Appliquer au personnage", "Auf Figur anwenden", "应用到角色形象",
        "Aplicar à imagem do personagem", "Applica all'immagine del personaggio"],
    "revert_original": ["恢复原貌", "Revert", "元に戻す", "원상 복구", "استعادة الأصل",
        "मूल रूप बहाल करें", "Kembalikan asal", "คืนสภาพเดิม", "Eski haline getir",
        "Khôi phục gốc", "Restaurer l'original", "Original wiederherstellen", "恢复原貌",
        "Reverter ao original", "Ripristina originale"],
    "pick_source_first": ["先在 ① 选源人脸", "Pick a source face in ① first",
        "まず ① で元顔を選んでください", "먼저 ① 에서 소스얼굴을 선택하세요",
        "اختر وجه المصدر في ① أولاً", "पहले ① में स्रोत चेहरा चुनें",
        "Pilih wajah sumber di ① dulu", "เลือกใบหน้าต้นทางใน ① ก่อน",
        "Önce ① içinde kaynak yüz seçin", "Hãy chọn khuôn mặt nguồn ở ① trước",
        "Choisissez d'abord un visage source en ①", "Zuerst in ① ein Quellengesicht wählen",
        "先在 ① 选源人脸", "Escolha o rosto de origem em ① primeiro",
        "Scegli prima un volto di origine in ①"],
    "no_target_yet": ['先在 ② 选角色或添加本地图片', 'Pick a character or add local images in ② first', 'まず ② でキャラクターを選ぶかローカル画像を追加してください', '먼저 ② 에서 캐릭터를 고르거나 로컬 이미지를 추가하세요', 'اختر شخصية أو أضف صورًا محلية في ② أولاً', 'पहले ② में किरदार चुनें या स्थानीय छवियाँ जोड़ें', 'Pilih karakter atau tambah gambar lokal di ② dulu', 'เลือกตัวละครหรือเพิ่มรูปใน ② ก่อน', 'Önce ② içinde karakter seçin veya yerel görsel ekleyin', 'Hãy chọn nhân vật hoặc thêm ảnh ở ② trước', "Choisissez d'abord un personnage ou des images locales en ②", 'Wählen Sie zuerst in ② eine Figur oder lokale Bilder.', '先在 ② 选角色或添加本地图片', 'Escolha um personagem ou imagens em ② primeiro', 'Scegli prima un personaggio o aggiungi immagini in ②'],
    "creative_free_hint": ['项目级「故事是什么」的全文描述,AI 用它生成匹配的章节内容(小说/短剧/漫画 都用)。生成出正文后自动锁定。', 'Project-level description of what the story is; AI uses it to generate matching chapters. Locks itself once real text has been generated.', 'プロジェクト単位の「物語は何であるか」の全文。AI がそれに合わせて本文を生成します。本文が生成されると自動的にロックされます。', '프로젝트 단위의 「무슨 이야기인가」 전문 설명. AI 가 이를 바탕으로 본문을 생성하며, 본문이 생성되면 자동으로 잠깁니다.', 'وصف على مستوى المشروع لماه هو القصة؛ يستخدمه الذكاء الاصطناعي لتوليد فصول مطابقة. يُقفل تلقائيًا بعد توليد نص فعلي.', 'प्रोजेक्ट स्तर पर यह बताने का विवरण कि कहानी क्या है; AI इसे उपयुक्त अध्याय बनाने के लिए उपयोग करता है। वास्तविक पाठ बनने पर अपने आप लॉक हो जाता है।', 'Deskripsi tingkat proyek apa yang ceritanya; AI memakainya untuk membuat bab yang sesuai. Terkunci otomatis setelah teks nyata dihasilkan.', 'คำอธิบายระดับโครงการว่าเรื่องนี้คืออะไร AI ใช้สร้างเนื้อหาให้ตรงกัน และจะล็อกอัตโนมัติเมื่อมีข้อความจริงถูกสร้างแล้ว', 'Proje düzeyinde hikâyenin ne olduğunun tam açıklaması; AI bölümleri buna göre üretir. Gerçek metin üretildikten sonra kendiliğinden kilitlenir.', 'Mô tả ở cấp dự án về nội dung câu chuyện; AI dùng nó để sinh nội dung phù hợp. Tự khóa sau khi đã sinh văn bản thật.', "Description à l'échelle du projet de ce qu'est l'histoire ; l'IA s'en sert pour générer des chapitres cohérents. Verrouillé automatiquement dès qu'un vrai texte est produit.", 'Projektweite Beschreibung dessen, was die Geschichte ist; die KI nutzt sie für passende Kapitel. Sperrt sich automatisch, sobald echter Text erzeugt wurde.', '项目级「故事是什么」的全文描述,AI 用它生成匹配的章节内容;生成出正文后自动锁定。', 'Descrição no nível do projeto do que é a história; a IA usa-a para gerar capítulos correspondentes. Bloqueia-se após gerar texto real.', "Descrizione a livello di progetto di cosa sia la storia; l'IA la usa per generare capitoli coerenti. Si blocca dopo aver generato testo reale."],
    "creative_locked_hint": ["已按这份创意生成过正文,创意描述已锁定不可修改(改它会让后续章节与既有正文对不上)。如需调整请新建项目。",
        "Real text has already been generated from this brief, so it is locked to keep later chapters consistent. Create a new project to change it.",
        "この企画から既に本文を生成済みで、整合性を保つためロックされています。変更するには新規プロジェクトを作成してください。",
        "이 기획으로 이미 본문이 생성되어 이후 장과의 일관성을 위해 잠겨 있습니다. 바꾸려면 새 프로젝트를 만드세요.",
        "تم بالفعل توليد نص فعلي من هذا الوصف، لذا هو مقفل للحفاظ على اتساق الفصول اللاحقة. أنشئ مشروعًا جديدًا لتغييره.",
        "इस विवरण से पाठ पहले ही बन चुका है, इसलिए आगे के अध्यायों की स्थिरता बनाए रखने हेतु यह लॉक है। बदलने के लिए नया प्रोजेक्ट बनाएँ।",
        "Teks nyata sudah dihasilkan dari brief ini, jadi dikunci agar bab berikutnya tetap konsisten. Buat proyek baru untuk mengubahnya.",
        "สร้างข้อความจริงจากร่างนี้แล้ว จึงล็อกไว้เพื่อให้บทถัดไปสอดคล้องกัน หากต้องการเปลี่ยนให้สร้างโครงการใหม่",
        "Bu taslaktan gerçek metin üretildiği için sonraki bölümlerin tutarlılığı adına kilitlidir. Değiştirmek için yeni proje oluşturun.",
        "Đã tạo văn bản thật từ bản tóm tắt này nên bị khóa để các chương sau nhất quán. Hãy tạo dự án mới nếu muốn đổi.",
        "Du texte réel a déjà été produit à partir de ce brief : il est verrouillé pour garder la cohérence des chapitres suivants. Créez un nouveau projet pour le modifier.",
        "Aus diesem Entwurf wurde bereits echter Text erzeugt; er ist gesperrt, damit spätere Kapitel konsistent bleiben. Zum Ändern ein neues Projekt anlegen.",
        "已按这份创意生成过正文,为保持后续章节一致已锁定;改它请新建项目。",
        "Já foi gerado texto real a partir deste briefing; está bloqueado para manter a consistência dos próximos capítulos. Crie um novo projeto para alterar.",
        "Da questo brief è già stato generato testo reale; è bloccato per mantenere coerenti i capitoli successivi. Crea un nuovo progetto per cambiarlo."],
    "novel_settings": ["小说设定", "Novel settings", "小説設定", "소설 설정",
        "إعدادات الرواية", "उपन्यास सेटिंग्स", "Pengaturan novel", "การตั้งค่านิยาย",
        "Roman ayarları", "Cài đặt tiểu thuyết", "Réglages du roman", "Roman-Einstellungen",
        "Ajustes de novela", "Configurações do romance", "Impostazioni romanzo"],
    "novel_settings_tip": ["总纲 / 世界观 / 故事合约 / 分卷战略 / 章节计划 / 主要角色",
        "Outline / worldbuilding / story contract / volumes / chapter plan / main characters",
        "総綱 / 世界観 / 物語契約 / 巻戦略 / 章立て / 主要登場人物",
        "개요 / 세계관 / 이야기 계약 / 권 전략 / 장차트 계획 / 주요 인물",
        "المخطط العام / بناء العالم / عقد القصة / استراتيجية الأجزاء / خطة الفصول / الشخصيات الرئيسية",
        "रूपरेखा / वर्ल्डबिल्डिंग / कहानी का संक / खंड रणनीति / अध्याय योजना / मुख्य पात्र",
        "Garis besar / dunia / kontrak cerita / strategi volume / rencana bab / tokoh utama",
        "โครงเรื่อง / โลกทัศน์ / สัญญาเรื่อง / กลยุทธ์เล่ม / แผนบท / ตัวละครหลัก",
        "Ana hat / dünya kuramı / hikâye sözleşmesi / cilt stratejisi / bölüm planı / ana kişiler",
        "Dàn ý / xây dựng thế giới / hợp đồng truyện / chiến lược tập / kế hoạch chương / nhân vật chính",
        "Plan général / univers / contrat narratif / stratégie de volumes / plan des chapitres / personnages principaux",
        "Gliederung / Weltbau / Storyvertrag / Bandstrategie / Kapitelplan / Hauptfiguren",
        "Esquema / construcción del mundo / contrato narrativo / estrategia de volúmenes / plan de capítulos / personajes",
        "Estrutura / construção do mundo / contrato da história / estratégia de volumes / plano de capítulos / personagens",
        "Struttura / worldbuilding / contratto narrativo / strategia dei volumi / piano dei capitoli / personaggi"],
    "u_custom_ellipsis": ["自定义…", "Custom…", "カスタム…", "사용자 지정…", "مخصص…", "कस्टम…",
                          "Kustom…", "กำหนดเอง…", "Özel…", "Tùy chỉnh…", "Personnalisé…",
                          "Benutzerdefiniert…", "Personalizado…", "Personalizado…", "Personalizzato…"],
    # ── 状态 ──
    "u_pending": ["待开始", "Not started", "未開始", "시작 전", "لم يبدأ", "शुरू नहीं हुआ", "Belum mulai",
                  "ยังไม่เริ่ม", "Başlanmadı", "Chưa bắt đầu", "Non démarré", "Nicht begonnen",
                  "Sin iniciar", "Não iniciado", "Non iniziato"],
    "u_running": ["进行中", "In progress", "進行中", "진행 중", "قيد التنفيذ", "प्रगति पर", "Berjalan",
                  "กำลังดำเนินการ", "Devam ediyor", "Đang chạy", "En cours", "In Bearbeitung",
                  "En curso", "Em andamento", "In corso"],
    "u_done": ["已完成", "Done", "完了", "완료", "مكتمل", "पूर्ण", "Selesai", "เสร็จสิ้น", "Tamamlandı",
               "Đã xong", "Terminé", "Fertig", "Hecho", "Concluído", "Completato"],
    "u_failed": ["失败", "Failed", "失敗", "실패", "فشل", "विफल", "Gagal", "ล้มเหลว", "Başarısız",
                 "Thất bại", "Échec", "Fehlgeschlagen", "Fallido", "Falhou", "Fallito"],
    # ── 画幅 / 面孔文化 ──
    "u_ratio_16_9": ["16:9 · 横屏", "16:9 · Landscape", "16:9 · 横", "16:9 · 가로", "16:9 · أفقي",
                     "16:9 · क्षैतिज", "16:9 · Lanskap", "16:9 · แนวนอน", "16:9 · Yatay",
                     "16:9 · Ngang", "16:9 · Paysage", "16:9 · Querformat", "16:9 · Horizontal",
                     "16:9 · Horizontal", "16:9 · Orizzontale"],
    "u_ratio_9_16": ["9:16 · 竖屏", "9:16 · Portrait", "9:16 · 縦", "9:16 · 세로", "9:16 · عمودي",
                     "9:9 · लंबवत", "9:16 · Potret", "9:16 · แนวตั้ง", "9:16 · Dikey",
                     "9:16 · Dọc", "9:16 · Portrait", "9:16 · Hochformat", "9:16 · Vertical",
                     "9:16 · Vertical", "9:16 · Verticale"],
    "u_ratio_1_1": ["1:1 · 方形", "1:1 · Square", "1:1 · 正方形", "1:1 · 정사각형", "1:1 · مربع",
                    "1:1 · वर्गाकार", "1:1 · Persegi", "1:1 · สี่เหลี่ยมจัตุรัส", "1:1 · Kare",
                    "1:1 · Vuông", "1:1 · Carré", "1:1 · Quadrat", "1:1 · Cuadrado",
                    "1:1 · Quadrado", "1:1 · Quadrato"],
    "u_ratio_adaptive": ["自适应", "Adaptive", "自動調整", "자동", "تكيفي", "अनुकूली", "Adaptif",
                         "ปรับอัตราส่วน", "Uyarlanabilir", "Thích ứng", "Adaptatif", "Adaptiv",
                         "Adaptativo", "Adaptativo", "Adattivo"],
    "u_eth_east_asian": ["东亚", "East Asian", "東アジア", "동아시아", "شرق آسيا", "पूर्व एशियाई",
                         "Asia Timur", "เอเชียตะวันออก", "Doğu Asyalı", "Đông Á", "Est-asiatique",
                         "Ostasiatisch", "Este Asiático", "Ásia Oriental", "Est-asiatica"],
    "u_eth_middle_eastern": ["中东", "Middle Eastern", "中東", "중동", "الشرق الأوسط", "मध्य पूर्वी",
                             "Timur Tengah", "ตะวันออกกลาง", "Orta Doğu", "Trung Đông",
                             "Moyen-Orient", "Naher Osten", "Oriente Medio", "Oriente Médio",
                             "Medio Oriente"],
    "u_eth_western": ["西方", "Western", "欧米", "서양", "غربي", "पश्चिमी", "Barat", "ตะวันตก",
                      "Batı", "Phương Tây", "Occidental", "Westeuropäisch", "Occidental",
                      "Ocidental", "Occidentale"],
    "u_eth_south_asian": ["南亚", "South Asian", "南アジア", "남아시아", "جنوب آسيا", "दक्षिण एशियाई",
                          "Asia Selatan", "เอเชียใต้", "Güney Asyalı", "Nam Á", "Sud-asiatique",
                          "Südasiatisch", "Surasiático", "Sul-asiático", "Sudasiatica"],
    "u_eth_latin": ["拉美", "Latin American", "ラテンアメリカ", "라틴 아메리카", "أمريكا اللاتينية",
                    "लैटिन अमेरिकी", "Amerika Latin", "ลาตินอเมริกา", "Latin Amerika", "Mỹ Latinh",
                    "Latino-américain", "Lateinamerikanisch", "Latinoamericano",
                    "Latino-americano", "Latinoamericana"],
    "u_eth_african": ["非洲", "African", "アフリカ", "아프리카", "أفريقي", "अफ्रीकी", "Afrika",
                      "แอฟริกา", "Afrikalı", "Châu Phi", "Africain", "Afrikanisch", "Africano",
                      "Africano", "Africano"],
    "u_eth_mixed": ["混合", "Mixed", "ミックス", "혼합", "مختلط", "मिश्रित", "Campuran", "ผสม",
                    "Karma", "Hỗn hợp", "Mixte", "Gemischt", "Mixto", "Misto", "Misto"],
    # ── 审校 / 台账 ──
    "u_review_n": ["审校 {0} 项", "{0} review issues", "レビュー {0} 件", "검수 {0}건",
                   "{0} ملاحظات مراجعة", "{0} समीक्षा मुद्दे", "{0} masalah tinjauan",
                   "พบปัญหาตรวจ {0} รายการ", "{0} inceleme bulgusu", "{0} vấn đề kiểm tra",
                   "{0} points de révision", "{0} Prüfpunkte", "{0} incidencias de revisión",
                   "{0} questões de revisão", "{0} rilievi di revisione"],
    "u_ledger": ["状态台账", "State ledger", "状態台帳", "상태 장부", "سجل الحالة", "स्थिति बही",
                 "Catatan status", "บัญชีสถานะ", "Durum kaydı", "Sổ trạng thái",
                 "Registre d'état", "Zustandsprotokoll", "Registro de estado", "Registro de estado",
                 "Registro di stato"],
    "u_foreshadow": ["伏笔台账", "Foreshadow ledger", "伏線台帳", "복선 장부", "سجل الإشارات التمهيدية",
                     "संकेत बही", "Catatan foreshadow", "บัญชีการปูเดา", "İz örgütü", "Sổ dư bối",
                     "Registre des indices", "Vorspann-Register", "Registro de pistas",
                     "Registro de pistas", "Registro di anticipazioni"],
    # ── 变体 ──
    "u_variants": ["造型变体", "Style variants", "バリエーション", "스타일 변형", "تنوعات المظهر",
                   "वेरिएंट", "Varian gaya", "รูปแบบลักษณะ", "Varyantlar", "Biến thể phong cách",
                   "Variantes de style", "Stilvarianten", "Variantes de estilo",
                   "Variantes de estilo", "Varianti di stile"],
    # ── 分镜工作台 ──
    "u_task_list": ["视频任务列表", "Video task list", "動画タスク一覧", "비디오 작업 목록",
                    "قائمة مهام الفيديو", "वीडियो कार्य सूची", "Daftar tugas video",
                    "รายการงานวิดีโอ", "Video görev listesi", "Danh sách tác vụ video",
                    "Liste des tâches vidéo", "VideAufgabenliste", "Lista de tareas de vídeo",
                    "Lista de tarefas de vídeo", "Elenco attività video"],
    "u_video_prompt": ["视频提示词", "Video prompt", "動画プロンプト", "비디오 프롬프트",
                       "مطالبة الفيديو", "वीडियो प्रॉम्प्ट", "Prompt video", "พรอมต์วิดีโอ",
                       "Video istemi", "Prompt video", "Invite vidéo", "Video-Prompt",
                       "Aviso de vídeo", "Prompt de vídeo", "Prompt video"],
    "u_bound_refs": ["绑定参考图", "Bound references", "バインド参考図", "연결 참고 이미지",
                     "الصور المرجعية المرتبطة", "बंधी संदर्भ चित्र", "Referensi terikat",
                     "ภาพอ้างอิงที่ผูก", "Bağlı referanslar", "Ảnh tham chiếu đã liên kết",
                     "Références liées", "Gebundene Referenzen", "Referencias vinculadas",
                     "Referências vinculadas", "Riferimenti collegati"],
    "u_comic_style": ["画风", "Art style", "画風", "화풍", "النمط الفني", "कला शैली", "Gaya seni",
                      "สไตล์ศิลป์", "Sanat stili", "Phong cách nghệ thuật", "Style artistique",
                      "Künstlerischer Stil", "Estilo artístico", "Estilo artístico",
                      "Stile artistico"],
    "u_stitch_long": ["拼接长图", "Stitch long image", "長尺画像を結合", "긴 이미지 이어붙이기",
                      "دمج الصورة الطويلة", "लंबी छवि संयोजन", "Gabungkan gambar panjang",
                      "ต่อภาพยาว", "Uzun görseli birleştir", "Ghép ảnh dài", "Fusionner la bande dessinée",
                      "Langes Bild zusammenfügen", "Unir imagen larga", "Juntar imagem longa",
                      "Unisci immagine lunga"],
    "u_whole_chapter": ["整章处理", "Whole chapter", "章全体", "장 전체", "الفصل كاملاً", "पूरा अध्याय",
                        "Seluruh bab", "ทั้งบท", "Tüm bölüm", "Toàn chương", "Chapitre entier",
                        "Ganzes Kapitel", "Capítulo completo", "Capítulo inteiro", "Capitolo intero"],
    "u_ai_edit": ["✨ AI 修改", "✨ AI edit", "✨ AI 編集", "✨ AI 편집", "✨ تحرير بالذكاء",
                  "✨ AI संपादन", "✨ Edit AI", "✨ แก้ไขด้วย AI", "✨ AI düzenle", "✨ Sửa bằng AI",
                  "✨ Modification IA", "✨ KI-Bearbeitung", "✨ Edición IA", "✨ Edição IA",
                  "✨ Modifica IA"],
    "u_click_view": ["点击查看大图", "Click to view", "クリックで閲覧", "클릭하여 보기", "انقر للعرض",
                     "देखने के लिए क्लिक करें", "Klik untuk melihat", "คลิกเพื่อดู",
                     "Görüntülemek için tıkla", "Nhấn để xem", "Cliquez pour voir",
                     "Klicken zum Ansehen", "Haz clic para ver", "Clique para ver", "Clic per vedere"],
    "u_draft_btn": ["起草中", "Drafting", "下書き中", "초안 중", "جارٍ الصياغة", "प्रारूपण",
                    "Menyusun", "กำลังร่าง", "Taslaklanıyor", "Đang soạn", "Rédaction",
                    "Entwurf", "Redactando", "Redigindo", "Bozza"],
    # ── 工具页 ──
    "u_nav_face_swap": ["换脸", "Face swap", "顔入れ替え", "얼굴 교체", "تبديل الوجه", "चेहरा बदलें",
                        "Tukar wajah", "สลับใบหน้า", "Yüz değiştir", "Đổi mặt", "Échange de visage",
                        "Gesichtstausch", "Cambio de rostro", "Troca de rosto", "Scambio volto"],
    "u_nav_merger": ["合并", "Merger", "結合", "병합", "دمج", "विलय", "Gabung", "รวม", "Birleştir",
                     "Hợp nhất", "Fusion", "Zusammenführen", "Fusionar", "Mesclar", "Unisci"],
    "u_storage": ["存储", "Storage", "ストレージ", "저장소", "التخزين", "भंडारण", "Penyimpanan",
                  "พื้นที่จัดเก็บ", "Depolama", "Bộ nhớ", "Stockage", "Speicher", "Almacenamiento",
                  "Armazenamento", "Archiviazione"],
    "u_free_space": ["剩余可用", "Free space", "空き容量", "여유 공간", "المساحة الحرة", "खाली जगह",
                     "Ruang kosong", "พื้นที่ว่าง", "Boş alan", "Dung lượng trống", "Espace libre",
                     "Freier Speicher", "Espacio libre", "Espaço livre", "Spazio libero"],
    "u_path": ["数据目录", "Data directory", "データディレクトリ", "데이터 디렉터리",
               "دليل البيانات", "डेटा निर्देशिका", "Direktori data", "ไดเรกทอรีข้อมูล",
               "Veri dizini", "Thư mục dữ liệu", "Répertoire de données", "Datenverzeichnis",
               "Directorio de datos", "Diretório de dados", "Directory dati"],
    "u_auto_gen": ["正在自动生成首集内容…", "Generating first episode…", "第1集を自動生成中…",
                   "첫 화 자동 생성 중…", "جارٍ إنشاء الحلقة الأولى…", "पहला अध्याय स्वतः बना रहा है…",
                   "Sedang membuat episode pertama…", "กำลังสร้างตอนแรก…", "İlk bölüm oluşturuluyor…",
                   "Đang tạo tập đầu…", "Génération du premier épisode…", "Erste Folge wird erstellt…",
                   "Generando primer episodio…", "Gerando primeiro episódio…",
                   "Generazione del primo episodio…"],
}


def ui_lookup(lang: str, key: str) -> str | None:
    """查 UI 补充词典;未命中返回 None(交由主词典/回退处理)。"""
    row = S.get(key)
    if not row:
        return None
    try:
        return row[LANGS.index(lang)]
    except (ValueError, IndexError):
        return row[0]